//calabresa > saindo pizza de calabresa
//frango > saindo pizza de frango
//queijo > saindo pizza de queijo

let saborPizza = "frango" //hardcode

switch(saborPizza){
    case "calabresa":
        console.log("Saindo de pizza de calabresa");
        break;
    case "frango":
        console.log("Saindo pizza de frango");
        break;
    case "queijo":
        console.log("Saindo pizza de queijo");
        break;
    default:
        console.log("@@@@@ Sabor de pizza indisponivel @@@@@");
}     